services:
  mongodb:
    image: mongo:7
    container_name: careernest-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - careernest-mongo:/data/db

volumes:
  careernest-mongo:
